version: '3'
services:
        web:
                image: projectskin
                build: .
                ports:
                        - "8024:8024"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
